### ISSUE TITLE
希望生日提醒显示为：某某79岁生日

### ISSUE THREAD

**Issue by jeep869** [Crazysiri/chineseholiday#1]
希望生日提醒增加年纪提醒，例如某某79岁生日。因为真记不住长辈多少岁数了。我自己多少岁也是稀里糊涂的，恳请大神实现这个需求，谢谢！设置的是时候只要设置出生日子，这样结婚纪念日等类似的可以通用

**Comment by Crazysiri** [comment]
好的，我最近考虑一下实现哈

**Comment by honentan** [comment]
好建议

**Comment by Crazysiri** [comment]
已经实现
