### ISSUE TITLE
卡片和 calculate_age 出错

### ISSUE THREAD

**Issue by WalterDSU** [Crazysiri/chineseholiday#10]
楼主, 卡片GitHub提示Uncaught TypeError: Cannot read property 'length' of undefined提示这个属性错误了.
另外, 
参考配置里面, 这部分有问题.
calculate_age:
    	- date: '2022-10-10 10:23:10'
          name: 'aa和bb结婚两周年'
提示这样错误.
duplicated mapping key at line 128, column 8:
        	  name: 'aa和bb结婚两周年'

**Comment by Crazysiri** [comment]
能否把整个配置文件发一下截个图，我看看缩进，关键的信息你可以用 xxx什么的替代掉

**Comment by Crazysiri** [comment]
报错信息也截个图，我方便查问题，这样我看不出什么问题的麻烦了啊

**Comment by Crazysiri** [comment]
尝试改了一下 卡片的问题，不知道行不行，你可以拉一下最新代码试一下
