### ISSUE TITLE
报这个错误是什么问题

### ISSUE THREAD

**Issue by 123152** [Crazysiri/chineseholiday#11]
Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 15:47:27 (27 occurrences)
Last logged: 16:19:23

http://xxxxxxxx/local/custom-lovelace/ch_calendar-card/ch_calendar-card.js:250:19 Uncaught TypeError: Cannot read properties of undefined (reading 'term')
http://xxxxxx/local/community/lovelace-animated-background/animated-background.js:535:22 Uncaught TypeError: Cannot read properties of null (reading 'background')
http://xxxxxxx/local/community/lovelace-animated-background/animated-background.js:535:22 Uncaught TypeError: Cannot read property 'background' of null
:0:0 Script error.

**Comment by Crazysiri** [comment]
是不是有些 配置文件没设置？

**Comment by Crazysiri** [comment]
另外ha什么版本、有试过最新的代码么

**Comment by 123152** [comment]
版本core-2022.4.3 拉取了最新代码，有实体 但属性值里只有一个节假日

**Comment by yzxuyang** [comment]
2022.04.08，一个实体都没有了

**Comment by Crazysiri** [comment]
更新一下最新的代 @yzxuyang

**Comment by Crazysiri** [comment]
fixed
