### ISSUE TITLE
不啥年龄计算错误

### ISSUE THREAD

**Issue by wolfid1** [Crazysiri/chineseholiday#13]
生日设置的20120506  今年2023年 显示距10岁生日还有XXX天，应该是11岁啊

**Comment by Crazysiri** [comment]
稍后我看一下这个

**Comment by wolfid1** [comment]
算的应该是当前的年龄，而不是下一外生日时的年龄。
但这个显示，按理说应该是生日时该几岁才对

**Comment by Crazysiri** [comment]
这里计算的是周岁，虚岁是12，周岁是10，周岁：过一个生日长一岁。虚岁：出生就1岁，每过春节长一岁。但这里确实应该显示11（即将过的生日）ok，回头我改一下哈哈哈

**Comment by Crazysiri** [comment]
改过了，有空你在试试

**Comment by wolfid1** [comment]
可以了，非常赖斯！！

**Comment by WalterDSU** [comment]
大佬这个问题, 又出现了, 阳历的纪念日, 还是少了一岁.
