### ISSUE TITLE
再请教一个问题 notify_script_name: 'test'

### ISSUE THREAD

**Issue by wolfid1** [Crazysiri/chineseholiday#15]
就是下面通知 test这段代码放啥地方啊？

test:
  sequence:
    - service: notify.mobile_app_xxx
      data_template:
        title: "节假日提醒"
        message: "{{ message }}"

**Comment by Crazysiri** [comment]
到达指定节日会触发这个脚本
写在scripts.yaml里即可，没有就创建一个，一般这个文件和configuration.yaml一个地方
1. notify.xx 是你需要被调用的服务
2. title 是通知的标题
3. message:{{ message }} 这里就是固定的写法

**Comment by Crazysiri** [comment]
最后在 配置chineseholiday的地方 配置 notify_script_name 为 test（你上面评论的是test，也可以改成其他的）

**Comment by wolfid1** [comment]
比如我设置 
    notify_times: 
        - "09:10:00"
        - "14:00:00"
    notify_principles:
      '14|7|1':
        - date: "0222"

意思应该是在2月22号前的14天 7天 1天 的早上9点10和下午2点会分别提示？
但提示内容 message: "{{ message }}" 在什么地方设置的呢？比如0222是个什么节?

**Comment by Crazysiri** [comment]
0222一般是你在 solar_anniversary lunar_annicersary设置的节日 或者自带的传统节假日（例如0214情人节）

**Comment by wolfid1** [comment]
懂了，谢谢。
那感觉在solar_anniversary lunar_annicersary设置的每组日期里放一个开关是否通知就行了，省得下面再设置一次

**Comment by Crazysiri** [comment]
> 懂了，谢谢。
> 
> 那感觉在solar_anniversary lunar_annicersary设置的每组日期里放一个开关是否通知就行了，省得下面再设置一次

嗯，你说的这个好像有道理哈哈哈，我回头考虑一下
