### ISSUE TITLE
节日 和 节气 每天有显示着上一次更新的

### ISSUE THREAD

**Issue by westwoon** [Crazysiri/chineseholiday#16]
节日 和 节气 每天有显示着上一次更新的。直到下个 节日 或 节气来到才更新，然后又再一直显示着直到下一个更新。
我觉得 节日 和 节气 应该是在当天显示而已，然后隔天就需要没有显示才对。
麻烦你检查一下。
目前HA版本是2023.2.1

**Comment by Crazysiri** [comment]
有截图么，我其实没看太懂，是不是在某个时间之前是上一日的，在某个时间之后就更新了？

**Comment by westwoon** [comment]
抱歉，我忘了载图。从启HA节日 和 节气 就正常显示了。但是如果到了某天有节日 或 节气，当天显示后，它又再一直显示到某天的新节日 或 节气。
比如
正月十四
节日：-
节气: 立春

到了某天 （正月十五），节气没更新如下：
节日：元宵节
节气: 立春

到了某天 （正月廿七），节日和节气还是没更新如下：
节日：元宵节
节气: 立春

再到了某天（正月廿九），节日没更新如下：
节日：元宵节
节气: 雨水

**Comment by Crazysiri** [comment]
ok，这个情况我看看哈。可能没注意

> 抱歉，我忘了载图。重启HA节日 和 节气 就正常显示了。但是如果到了某天有节日 或 节气，当天显示后，它又再一直显示到某天的新节日 或 节气。
> 
> 比如
> 
> 正月十四
> 
> 节日：-
> 
> 节气: 立春
> 
> 
> 
> 到了某天 （正月十五），节气没更新如下：
> 
> 节日：元宵节
> 
> 节气: 立春
> 
> 
> 
> 到了某天 （正月廿七），节日和节气还是没更新如下：
> 
> 节日：元宵节
> 
> 节气: 立春
> 
> 
> 
> 再到了某天（正月廿九），节日没更新如下：
> 
> 节日：元宵节
> 
> 节气: 雨水

**Comment by Crazysiri** [comment]
拉取一下最新代码看看

**Comment by westwoon** [comment]
谢谢， 我今晚试试。
