### ISSUE TITLE
Polymer will be removed

### ISSUE THREAD

**Issue by devang2** [Crazysiri/chineseholiday#17]
WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer

**Comment by WalterDSU** [comment]
大佬出现下面错误了. 卡片不能用了...能否可以适配一下. 很喜欢这个卡片.  楼主有空搞搞. 我自己试过改, 但是, 还是不行. 你要不帮忙看看. 谢谢.
WARNING: Polymer will be removed from window in Home Assistant 2023.5.

**Comment by Crazysiri** [comment]
哦哦好的哈，最近有空我搞一下，最近上班太忙了，这么久了还有人在用哈哈哈感谢

**Comment by WalterDSU** [comment]
谢谢大佬, 我们在qq聊吧. 我自己尝试改过了. 小弟不才, 没改好. 其实卡片很好用, 这种简单又实用的功能.我还没有发现还有替代品. 就一直用了. 另外, 就是UI简单点. 如果可以美化一下, 或者再可以用UI设置就更好.
