### ISSUE TITLE
如果农历生日是12月，对应的国历是下一年，但到了下一年会直接路过上一年12月的农历生日

### ISSUE THREAD

**Issue by jjss520** [Crazysiri/chineseholiday#20]
如题

**Comment by Crazysiri** [comment]
路过是指跳过？有具体的例子不？具体表现是什么？是哪块显示的异常么

**Comment by Crazysiri** [comment]
> 如题

**Comment by lucienyida** [comment]
![111](https://github.com/Crazysiri/chineseholiday/assets/96853173/f0828979-0950-4906-bf8e-7fc36006bfd1)
![2222](https://github.com/Crazysiri/chineseholiday/assets/96853173/f9603c28-dda5-4cf3-87fc-284e9856ca2a)

跳过是这样得，比如我设置的农历12月18生日，现在不是还有23天，但是卡片上显示是380多天，直接跳过了

**Comment by jjss520** [comment]
是这样，农历12月或者11月，对应国历1月或者2月，本身在2023年能显示对应的距离生日多少天，但在2024，会直接路过一次的，而显示下一年的，应该是逻辑上有点问题

**Comment by lucienyida** [comment]
> 是这样，农历12月11月，对应国历1月或者2月，本身在2023年可以显示对应的距离生日多少天，但在2024年，会直接路过一次的，而显示下一年的，应该是逻辑上有点问题

我现在设置公历好像没问题了

**Comment by Crazysiri** [comment]
对这块确实有问题，我修复一下

**Comment by Crazysiri** [comment]
0.2.0.3 已修复 @jjss520 @lucienyida

**Comment by jjss520** [comment]
> 0.2.0.3 已修复 @jjss520 @lucienyida

神速，大佬牛批
