### ISSUE TITLE
农历生日无法在卡片中显示

### ISSUE THREAD

**Issue by isw866** [Crazysiri/chineseholiday#22]
农历11月29日的生日无法在卡片中显示，请大佬看一下

**Comment by Crazysiri** [comment]
> 农历11月29日的生日无法在卡片中显示，请大佬看一下
是不是同一个时间段的生日之类的多于4条？配置能不能大概发一下

**Comment by isw866** [comment]
> > 农历11月29日的生日无法在卡片中显示，请大佬看一下
> > 是不是同一个时间段的生日之类的多于4条？配置能不能大概发一下

对的，同一月份有4条，
1109
1119
1121
1129

**Comment by Crazysiri** [comment]
> > > 农历11月29日的生日无法在卡片中显示，请大佬看一下
> 
> > > 是不是同一个时间段的生日之类的多于4条？配置能不能大概发一下
> 
> 
> 
> 对的，同一月份有4条，
> 
> 1109
> 
> 1119
> 
> 1121
> 
> 1129

都是农历啊？我用你这个一会试试

**Comment by isw866** [comment]
> > > > 农历11月29日的生日无法在卡片中显示，请大佬看一下
> > 
> > 
> > > > 是不是同一个时间段的生日之类的多于4条？配置能不能大概发一下
> > 
> > 
> > 对的，同一月份有4条，
> > 1109
> > 1119
> > 1121
> > 1129
> 
> 都是农历啊？我用你这个一会试试

是的，都是农历

**Comment by Hosiang1026** [comment]
农历生日配置多个，最多只显示3个，希望修复一下

**Comment by Crazysiri** [comment]
0.2.0.3 已修复 @isw866 @Hosiang1026
