### ISSUE TITLE
农历纪念日不显示

### ISSUE THREAD

**Issue by Gzzloveyyt** [Crazysiri/chineseholiday#23]
刚更新了最新版，农历纪念日不显示，麻烦看下！

![Uploading 1234.png…]()

**Comment by Gzzloveyyt** [comment]
![1234](https://github.com/Crazysiri/chineseholiday/assets/25847375/f2b5417e-2026-4ae1-9137-c85c5c9cf209)

**Comment by Crazysiri** [comment]
好的，这两天我看一下

**Comment by Gzzloveyyt** [comment]
@Crazysiri  而且好像上一个版本我设置的结婚纪念日是20180909  然后当时显示的结婚纪念日后面的几周年 好像也不对，是多一年还是少一年，你看下    应该是算错了

**Comment by Crazysiri** [comment]
> 你等先修复 出这个纪念日，让卡片显示， 正常设置农历12月25，那现在也不到12月25  卡片应该会显示才对，   卡片显示后你看下后面算的那个多少年对不对    我没记错的话是错的

好的我先看看

**Comment by Gzzloveyyt** [comment]
辛苦大佬！  @Crazysiri

**Comment by Gzzloveyyt** [comment]
我记得上个版本，也就是去年2023年，我快到结婚纪念日时，当时我设置的20180909，正常我应该是过5周年结婚纪念日，你看2018年9月初9结的婚    2019、2020、2021、2022、2023，到2023年当时应该是5周年，但是卡片显示的是6周年， 我想起来了，就给你说下具体情况，  可能计算时连2018年也算上了， 实际应该2018-2019才是第一年

**Comment by Gzzloveyyt** [comment]
2018.9.9-2019.9.9  一周年
2019.9.9-2020.9.9  二周年
2020.9.9-2021.9.9  三周年
2021.9.9-2022.9.9  四周年
2022.9.9-2023.9.9  五周年

所以去年应该显示是5周年才对

**Comment by Gzzloveyyt** [comment]
请问下作者多久能修复？@Crazysiri

**Comment by Crazysiri** [comment]
> 请问下作者多久能修复？@Crazysiri

周末，哥，平时特别忙

**Comment by Gzzloveyyt** [comment]
我上面图设置的果果生日20190201  农历的，  也不显示， 他这个生日是提前多长时间会显示，是因为跨年了吗？  过完春节就能显示了吗？

**Comment by Crazysiri** [comment]
0.2.0.5 修复农历不现实 @Gzzloveyyt 另外 2018.9.9 这个我试了lunar的配置，截止2024.1.21时，显示6周年应该没问题

**Comment by Gzzloveyyt** [comment]
@Crazysiri 我说的是我去年当时还没到纪念日的时候，他就显示是6周年了， 也就是2023年9月初9以前，  他就显示是距离结婚纪念日（6周年）还有XX 天，这种，  我先更新再试下吧。  有问题再跟你反馈

**Comment by Gzzloveyyt** [comment]
辛苦了
