### ISSUE TITLE
能否添加显示本周是年度的第几周

### ISSUE THREAD

**Issue by 596142041** [Crazysiri/chineseholiday#27]
![微信截图_20240309104027](https://github.com/Crazysiri/chineseholiday/assets/4958182/285ffdcc-3b79-4286-b9b0-7d74550a39e6)
如上

**Comment by 596142041** [comment]
周数已经添加了，怎么在卡片添加啊;在卡片属性里面已经能看着了。

**Comment by Crazysiri** [comment]
我帮你搞吧，你提个pr上来我先把你的周数代码合进去

**Comment by Crazysiri** [comment]
@596142041

**Comment by 596142041** [comment]
在lunar.py的420行添加了如下代码:
    def solar_week_number(self):#周数
        return "第"+str(datetime.datetime(int(solar_year), int(solar_month), int(solar_day)).isocalendar()[1]) + "周"

在sensor.py的518行添加如下代码:
self.attributes['week_number']   = self._lunar.solar_week_number()
        self.localizedAttributes['周数'] = self._lunar.solar_week_number()

**Comment by Crazysiri** [comment]
更新一下 
插件版本：0.2.0.6 
https://github.com/Crazysiri/chineseholiday/releases/tag/v0.2.0.6

卡片版本：0.2.2 
https://github.com/Crazysiri/chineseholiday_card/releases/tag/0.2.2

@596142041

**Comment by 596142041** [comment]
已经可以正常显示了，感谢！
