### ISSUE TITLE
是否是节假日的优化建议

### ISSUE THREAD

**Issue by shawn996** [Crazysiri/chineseholiday#30]
目前是否是节假日，是通过api接口获取的。其实api接口的作者，提供了[开源版本](https://gitee.com/web/holidays_api)的实现。在data目录下有一年的数据，通过这个数据就可以实现离线判断，会更稳定些。可否对相关逻辑进行优化，使用这个相当于离线的版本来判断节假日。

**Comment by Crazysiri** [comment]
这个我考虑过，但这么搞每年都得升级一次插件了，有利有弊

**Comment by shawn996** [comment]
和目前的json缓存一样，系统自动缓存一次就行了。获取到了就用缓存的，获取不到就用在线的。

**Comment by Crazysiri** [comment]
现在就是这个逻辑，只不过我现在缓存6个月的

**Comment by shawn996** [comment]
是的，现在的逻辑是从api取得最近6个月的，但如果从那个git中取得data一次就可以取得一年的，稳定性方面来说可能更好些。
