### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'chineseholiday'.

### ISSUE THREAD

**Issue by leo783x** [Crazysiri/chineseholiday#6]
No 'version' key in the manifest file for custom integration 'chineseholiday'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'chineseholiday

**Comment by Crazysiri** [comment]
@leo783x 你好，已经修复了

**Comment by leo783x** [comment]
辛苦
