### ISSUE TITLE
Sensor 离线

### ISSUE THREAD

**Issue by sephrioth** [Crazysiri/chineseholiday#7]
今天闹钟没响， 发现是 sensor 离线了好一会..   我没用默认的 card 来显示，只是用了里面的属性值来控制。

> Logger: homeassistant.util.async_
Source: util/async_.py:132
First occurred: May 29, 2021, 12:00:15 AM (3 occurrences)
Last logged: 12:00:15 AM
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for chineseholiday doing I/O at custom_components/chineseholiday/holiday.py, line 428: res = self.session.get(url, headers=headers)

**Comment by Crazysiri** [comment]
这个是警告没关系，离线可能是别的原因引起的。看看有没有别的错误。或者你可以先看看有没有实体在上面

**Comment by Crazysiri** [comment]
@sephrioth

**Comment by sephrioth** [comment]
> 这个是警告没关系，离线可能是别的原因引起的。看看有没有别的错误。或者你可以先看看有没有实体在上面

就是实体消失了。。。 但是我不知道是啥时候消失的， 那我开着继续观察下， 感谢回复。

**Comment by Crazysiri** [comment]
@sephrioth 好奇怪，你的ha什么版本的，消失了肯定有报错，不是warning。我得看看报错才知道

**Comment by sephrioth** [comment]
2021.5.5 的，我都是升级到最新版。 因为我发现不见了， 我就直接去 log 里搜相关日志了， 可能还有更多的错误日志我没注意。 我重启之前把log都清了， 所以只能等下次再出现了在反馈了。。。 还专门写了个通知自动化来追踪
。。。

**Comment by Crazysiri** [comment]
@sephrioth 那肯定是升级后的问题了，我也是昨天才升级的2021.5.5 暂时还好。估计你是升级了最新的代码吧？应该是昨天的还是前天的。

**Comment by sephrioth** [comment]
我刚又升级了你这边的最新的代码， 先观察看看～

**Comment by Crazysiri** [comment]
@sephrioth 好的你先更新一下看看，再有问题再发出来
