### ISSUE TITLE
卡片怎么使用

### ISSUE THREAD

**Issue by ilongjiang** [Crazysiri/chineseholiday#9]
卡片怎么使用

**Comment by Crazysiri** [comment]
1.如果是 ui-lovelace.yaml 配置的：

resources:
  - type: module
    url: /local/custom-lovelace/ch_calendar-card/ch_calendar-card.js

卡片配置
  - type: 'custom:ch_calendar-card'
    entity: sensor.holiday                                        
    icons: /local/custom-lovelace/ch_calendar-card/icons/

2.如果是通过管理页面配置的：
左边‘配置’-> Lovelace-> 资源
把上面resources填进去
然后 组件选自定义通过代码配置，把卡片配置的代码填进去

@ilongjiang

**Comment by ilongjiang** [comment]
谢谢，我配置的时候url地址没写对。现在按照您给的方法配好了。

**Comment by Crazysiri** [comment]
客气

**Comment by ben-august** [comment]
2022年11月前来提问，现在homeassistant文件结构变化很大，要如何添加呢？我看release中的目录结构和现在版本的hass对不上。谢谢🙏
